myName = input("What's your name?: ")
favFood = input("what's your favorite food?: ")
favMusic = input("What's your favorite music?: ")
live = input("Where do you live?: ")
print()
print("You are")
print(myName)
print("You're probably hungry for")
print(favFood)
print("and you're definitely getting your groove on to")
print(favMusic)
print("living in the amazing")
print(live)