foodName = input("Name a food: ")
plantName = input("Name a type of plant: ")
cookMethod = input("Name a method of cooking: ")
burnFood = input("What word describes burned food: ")
item = input("Name a DIY item: ")
print()
print("MENU")
print(cookMethod, foodName, "with", burnFood, plantName, "on a bed of", item)